title: Choi Hyeongwon
email: cgd0502@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Themed by ejjoo
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://choihw0502.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: choihw0502
highlighter: rouge
svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
